CREATE TYPE "transcription_job_status" AS ENUM ('queued', 'processing', 'completed', 'failed');
CREATE TABLE "users" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "email" text NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX "users_email_unique" ON "users" ("email");
CREATE TABLE "guest_sessions" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "token_hash" text NOT NULL, "expires_at" timestamptz NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX "guest_sessions_token_hash_unique" ON "guest_sessions" ("token_hash");
CREATE INDEX "guest_sessions_expires_at_idx" ON "guest_sessions" ("expires_at");
CREATE TABLE "recordings" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "user_id" uuid REFERENCES "users"("id") ON DELETE cascade, "guest_session_id" uuid REFERENCES "guest_sessions"("id") ON DELETE cascade, "object_key" text NOT NULL, "original_filename" text, "media_type" text, "duration_ms" bigint, "expires_at" timestamptz, "created_at" timestamptz DEFAULT now() NOT NULL, CONSTRAINT "recordings_owner_check" CHECK (num_nonnulls("user_id", "guest_session_id") = 1));
CREATE INDEX "recordings_user_id_idx" ON "recordings" ("user_id");
CREATE INDEX "recordings_guest_session_id_idx" ON "recordings" ("guest_session_id");
CREATE TABLE "transcription_jobs" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "recording_id" uuid NOT NULL REFERENCES "recordings"("id") ON DELETE cascade, "status" "transcription_job_status" DEFAULT 'queued' NOT NULL, "attempts" bigint DEFAULT 0 NOT NULL, "error_code" text, "error_message" text, "started_at" timestamptz, "completed_at" timestamptz, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE INDEX "transcription_jobs_recording_id_idx" ON "transcription_jobs" ("recording_id");
CREATE INDEX "transcription_jobs_status_idx" ON "transcription_jobs" ("status");
CREATE TABLE "transcripts" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "recording_id" uuid NOT NULL REFERENCES "recordings"("id") ON DELETE cascade, "language" text, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX "transcripts_recording_id_unique" ON "transcripts" ("recording_id");
CREATE TABLE "speakers" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "transcript_id" uuid NOT NULL REFERENCES "transcripts"("id") ON DELETE cascade, "engine_speaker_id" text NOT NULL, "label" text NOT NULL);
CREATE UNIQUE INDEX "speakers_transcript_engine_id_unique" ON "speakers" ("transcript_id", "engine_speaker_id");
CREATE TABLE "transcript_segments" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "transcript_id" uuid NOT NULL REFERENCES "transcripts"("id") ON DELETE cascade, "speaker_id" uuid REFERENCES "speakers"("id") ON DELETE set null, "start_ms" bigint NOT NULL, "end_ms" bigint NOT NULL, "text" text NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, CONSTRAINT "transcript_segments_timestamps_check" CHECK ("start_ms" >= 0 AND "end_ms" >= "start_ms"));
CREATE INDEX "transcript_segments_transcript_id_idx" ON "transcript_segments" ("transcript_id");
CREATE INDEX "transcript_segments_speaker_id_idx" ON "transcript_segments" ("speaker_id");
